language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build
  - cargo test
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --release
