language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo build
  - cargo test
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo build --release
